dist: xenial
#hey

install:
 - sudo apt-get install python
before_script:
  - composer self-update -q
  - if [ -n "$shubh" ]; then composer config github-oauth.github.com ${shubh}; fi;
  - composer show -i
script: 
 - echo "shubham"
deploy:
 - provider: pages
 - skip_cleanup: true
 - github_token: $shubh
 - keep_history: true
 - on:
    branch:
     - master
